### ISSUE TITLE
laravel/framework 9.35+ action middleware not being resolved

### ISSUE THREAD

**Issue by jalt007** [lorisleiva/laravel-actions#199] opened 2022-10-13 13:05 UTC
Hello!

From `laravel/framework` 9.35+ actions run `asController` have a regression in behaviour.

Controller middleware is not being resolved properly, leading to things like route model binding not working.

Due to: 
https://github.com/laravel/framework/commit/6cdf03e661a2a8b9b4ea2cc7d503e1d6a09bf5dc#diff-efe2a07687b9b821bbd99ae38a9329253f032e6df04bdea02bba9303a2b2beadL1084-R1103

Current workaround: make actions extend `Illuminate\Routing\Controller`.

Not sure how best to proceed, I'm happy using the workaround mentioned above at the moment.

**Comment by JasperTey** [comment] 2022-10-13 23:24
I can confirm the same on one of my projects where I'm using a few actions `asController`. Thanks for the suggested workaround in the meantime, it saved me some time hunting down the root cause.

**Comment by lorisleiva** [comment] 2022-10-14 11:17
😢 Thanks for raising this! I don't think there's anything Laravel Actions can do aside from making a PR to Laravel to relax that last if statement.

**Comment by PaulMenheere** [comment] 2022-10-14 13:07
Was issue created at laravel/framework ?

**Comment by lorisleiva** [comment] 2022-10-14 13:15
Yes, in this PR: https://github.com/laravel/framework/pull/44516

**Comment by PaulMenheere** [comment] 2022-10-14 13:28
No, what I meant to say was. Was an issue logged with Laravel about this issue.
Something like `'Can use invokable classes without extending it with Controller'`
or `how to use HasMiddleware`

**Comment by lorisleiva** [comment] 2022-10-14 13:40
Oh sorry. No, not yet, I've been trying to fix it on Laravel Actions first.

I've been trying to hijack the middleware logic but I sadly end up running route middleware twice. See #200.

**Comment by lorisleiva** [comment] 2022-10-14 13:54
I'm writing a PR for laravel/framework right now.

**Comment by PaulMenheere** [comment] 2022-10-14 13:55
I've done some debugging on my own.

My conclusions
1. Middleware will be detected with/without the `extends Controller` or `implements hasMiddleware`
2. using the current `__invoke` method will fail the `SubstituteBindings` Middleware, it will see `...$arguments` which it can't bind
3. using the `Route::get('route', [CLASS, 'asController`]` will make everything work nicely


In short the [__invoke](https://github.com/lorisleiva/laravel-actions/blob/4090b937630ce4f4e72fcac6062bac1dee21ebb5/src/Concerns/AsController.php#L12) is the problem

**Comment by lorisleiva** [comment] 2022-10-14 14:01
That's not quite true. The `ControllerDecorator` [updates the `action` property](https://github.com/lorisleiva/laravel-actions/blob/4090b937630ce4f4e72fcac6062bac1dee21ebb5/src/Decorators/ControllerDecorator.php#L103) of the route so that `SubstituteBindings` can work. The issue introduced by Laravel 9.35 has nothing to do with this.

**Comment by PaulMenheere** [comment] 2022-10-14 14:05
And I was so proud for finding this.
Anyway, for some reason with the laravel 9.35 the route paramters in `asController` don't work anymore

**Comment by lorisleiva** [comment] 2022-10-14 14:13
I've created a PR in `laravel/framework` that would fix this if it is merged. 🤞 

https://github.com/laravel/framework/pull/44590

**Comment by lorisleiva** [comment] 2022-10-17 18:58
PR merged on `laravel/framework`! 🎉 I still need to update the `AsController` trait so it includes an empty `getMiddleware` method for that second if statement to trigger. I'll do that as soon as I have a moment. Bear with me. 🌺

**Closed** 2022-10-20 17:51 UTC

**Comment by lorisleiva** [comment] 2022-10-20 17:59
Fix merged and released as `v2.4.1`. 🚀 

Let me know if you have any more issues. 🙏
