### ISSUE TITLE
WithAttributes will not let you Mock or PartialMock Action Objects

### ISSUE THREAD

**Issue by WorthLMS** [lorisleiva/laravel-actions#275] opened 2024-03-12 18:08 UTC
Trying to mock or partialMock any Action Object when the WithAttributes Trait attached throws

Received Mockery_#_App_Actions_Action::set(), but no expectations were specified

**Comment by Wulfheart** [comment] 2024-10-16 16:51
Seems to be a Mockery error and not related to Actions. I am going to close this issue until you provide more info and a reproduction repository.

**Closed by Wulfheart** 2024-10-16 16:51 UTC
