### ISSUE TITLE
Actions don't work with Octane

### ISSUE THREAD

**Issue by jedjones-uk** [lorisleiva/laravel-actions#202] opened 2022-10-18 12:36 UTC
Hi,

I've been testing actions for use with octane and it seems they don't work properly. The first run of an action goes to the html output, and the second and all subsequent requests to the same endpoint goes to the json output.

I think it has to do with the fact that `ControllerDecorator@__invoke` is not called subsequent requests but I've not really been able to trace it down to a specific set of code.

The subsequent requests also seem to go direct to the action itself.

**Comment by Spice-King** [comment] 2022-11-16 15:49
Going to tag in with the same problem.

As far as I can see, `ActionManager`'s `$extended` property is not getting cleared between runs, thus on the second run is not calling `app()->extend()`. Going to see if I find a solution and see about making a PR.

**Comment by Spice-King** [comment] 2022-11-16 17:58
Looks like I was right. Debating on how to make a PR, but this is the hack job of a listener does work when added to `config/octane.php` for the `RequestReceived` event if you're interested @jedjones-uk.
```php
<?php

namespace App\Listeners;

use Laravel\Octane\Events\RequestReceived;
use Lorisleiva\Actions\ActionManager;

class FixLaravelActionsOnOctane
{
    public function handle(RequestReceived $event)
    {
        $manager = $event->app->get(ActionManager::class);
        $r = new \ReflectionObject($manager);
        $p = $r->getProperty("extended");
        $p->setAccessible(true);
        $p->setValue($manager, []);
    }
}

```
Octane really seems to lack documentation about best practices for making packages with it, outside of this [bit on dependacy injection](https://laravel.com/docs/9.x/octane#dependency-injection-and-octane). Just no mention of the events or the included listeners for them that reset the pins for Laravel and it's first party packages.

**Comment by jedjones-uk** [comment] 2022-11-16 19:15
@Spice-King 

This is great work for tracing this down to a repeatable solution, I spent a while losing hair trying to figure out just where the key issue was. You fix works fine as a hack but a long term quality solution I think requires 2 changes.

1: Define some helper functions to determine if octane is in use like these: https://github.com/laravel/octane/issues/508#issuecomment-1096937174

2: when octane is in use, skip the `$this->isExtending($abstract)` call in the `extending` function for `ActionManager`

This would avoid the need for reflection and keeps everything in house.

Thanks again.

**Comment by ClaraLeigh** [comment] 2023-02-07 02:01
Been having weird routing issues lately. Dependancy and route binding working 99% of the time but occasionally failing. Turning off octane seems to have cleaned it up, wonder if its related to this

**Comment by Wulfheart** [comment] 2023-02-07 08:13
Do you have a reproduction repository?

**Comment by ClaraLeigh** [comment] 2023-02-16 05:09
@Wulfheart if you're asking me, I did all the notes and comments I had in the PR #221 
Ran out of time to work on it further for the moment

**Comment by binaryfire** [comment] 2023-02-16 09:08
Hi all. Should I be avoiding using this package in a complex app that's using Octane? I'm new to Laravel so it'd be hard for me to debug the kind of issues described here. Our app is headless and proxying several external APIs so Octane is essential... 

I really like the way this package could simplify our architecture but this has been open since October and another Octane-related issue has (https://github.com/lorisleiva/laravel-actions/issues/136) been open since 2021. So I'm beginning to think it might not play nicely with Octane in general?

**Comment by dmason30** [comment] 2023-06-21 21:46
HI all, This may have been fixed indirectly in https://github.com/lorisleiva/laravel-actions/releases/tag/v2.6.0 from my PR attempting to fix issues with octane and inline listeners/jobs. If someone can check and confirm that would be great.

**Closed** 2024-03-13 13:09 UTC
